import type { CelestialBodyData } from './solarTypes';

export const solarBodiesData: CelestialBodyData[] = [
  {
    id: 'sun',
    name: '太阳',
    type: 'star',
    radius: 1.2,
    orbitRadius: 0,
    rotationSpeed: 0.15,
    orbitSpeed: 0,
    color: '#facc15',
    description: '太阳是太阳系的中心恒星，为行星系统提供光和热。',
    diameter: '约 1,392,700 km',
    distanceFromSun: '0',
    orbitalPeriod: '不适用',
    rotationPeriod: '约 25 至 35 天',
    moons: '不适用',
  },
  {
    id: 'mercury',
    name: '水星',
    type: 'planet',
    radius: 0.16,
    orbitRadius: 2.1,
    rotationSpeed: 0.35,
    orbitSpeed: 1.6,
    color: '#a3a3a3',
    description: '水星是距离太阳最近的行星，表面温差极大。',
    diameter: '约 4,879 km',
    distanceFromSun: '约 0.39 AU',
    orbitalPeriod: '约 88 天',
    rotationPeriod: '约 58.6 天',
    moons: '0 颗',
  },
  {
    id: 'venus',
    name: '金星',
    type: 'planet',
    radius: 0.28,
    orbitRadius: 2.9,
    rotationSpeed: -0.25,
    orbitSpeed: 1.15,
    color: '#f5c16c',
    description: '金星拥有浓厚的大气层，是太阳系中表面温度最高的行星。',
    diameter: '约 12,104 km',
    distanceFromSun: '约 0.72 AU',
    orbitalPeriod: '约 225 天',
    rotationPeriod: '约 243 天（逆向自转）',
    moons: '0 颗',
  },
  {
    id: 'earth',
    name: '地球',
    type: 'planet',
    radius: 0.32,
    orbitRadius: 4,
    rotationSpeed: 1.2,
    orbitSpeed: 0.9,
    color: '#3b82f6',
    description: '地球是太阳系第三颗行星，也是目前已知唯一存在生命的行星。',
    diameter: '约 12,742 km',
    distanceFromSun: '约 1 AU',
    orbitalPeriod: '365.25 天',
    rotationPeriod: '约 23.9 小时',
    moons: '1 颗',
  },
  {
    id: 'moon',
    name: '月球',
    type: 'moon',
    radius: 0.11,
    orbitRadius: 0.75,
    rotationSpeed: 0.6,
    orbitSpeed: 2.2,
    color: '#cbd5e1',
    description: '月球是地球唯一的天然卫星，对地球潮汐和夜空观测具有重要影响。',
    diameter: '约 3,474 km',
    distanceFromSun: '随地球变化',
    orbitalPeriod: '约 27.3 天',
    rotationPeriod: '约 27.3 天',
    moons: '0 颗',
  },
  {
    id: 'mars',
    name: '火星',
    type: 'planet',
    radius: 0.24,
    orbitRadius: 5.2,
    rotationSpeed: 1.05,
    orbitSpeed: 0.72,
    color: '#ef4444',
    description: '火星因富含氧化铁而呈红色，是人类深空探索的重要目标。',
    diameter: '约 6,779 km',
    distanceFromSun: '约 1.52 AU',
    orbitalPeriod: '约 687 天',
    rotationPeriod: '约 24.6 小时',
    moons: '2 颗',
  },
  {
    id: 'jupiter',
    name: '木星',
    type: 'planet',
    radius: 0.72,
    orbitRadius: 7.1,
    rotationSpeed: 1.8,
    orbitSpeed: 0.38,
    color: '#d6a06a',
    description: '木星是太阳系中最大的行星，拥有显著的云带和大红斑。',
    diameter: '约 139,820 km',
    distanceFromSun: '约 5.2 AU',
    orbitalPeriod: '约 11.86 年',
    rotationPeriod: '约 9.9 小时',
    moons: '95+ 颗',
  },
  {
    id: 'saturn',
    name: '土星',
    type: 'planet',
    radius: 0.62,
    orbitRadius: 9.3,
    rotationSpeed: 1.55,
    orbitSpeed: 0.28,
    color: '#e6c27a',
    description: '土星以宏大的行星环闻名，是太阳系第二大行星。',
    diameter: '约 116,460 km',
    distanceFromSun: '约 9.58 AU',
    orbitalPeriod: '约 29.45 年',
    rotationPeriod: '约 10.7 小时',
    moons: '140+ 颗',
  },
  {
    id: 'uranus',
    name: '天王星',
    type: 'planet',
    radius: 0.42,
    orbitRadius: 11.2,
    rotationSpeed: -0.9,
    orbitSpeed: 0.2,
    color: '#67e8f9',
    description: '天王星呈蓝绿色，并以接近横躺的自转轴闻名。',
    diameter: '约 50,724 km',
    distanceFromSun: '约 19.2 AU',
    orbitalPeriod: '约 84 年',
    rotationPeriod: '约 17.2 小时（逆向）',
    moons: '27 颗',
  },
  {
    id: 'neptune',
    name: '海王星',
    type: 'planet',
    radius: 0.4,
    orbitRadius: 13,
    rotationSpeed: 1.0,
    orbitSpeed: 0.16,
    color: '#2563eb',
    description: '海王星是已知太阳系中距离太阳最远的行星，拥有强烈风暴系统。',
    diameter: '约 49,244 km',
    distanceFromSun: '约 30.1 AU',
    orbitalPeriod: '约 164.8 年',
    rotationPeriod: '约 16.1 小时',
    moons: '14 颗',
  },
];